import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

const ralewaySans = Raleway({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Resonanex Labs | Write-ups and Guides for Tech Advancement.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ralewaySans.className} antialiased selection:bg-theme selection:text-gray-50`}
      >
        {children}
      </body>
    </html>
  );
}
